name: Run Unit test
on:
  push:
    Branches: 
      - main

jobs:
  build:
    runs-on: ububtu-latest
    
    steps:
    - name: checkout repository
    uses: actions/checkout@v4

    - name: set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    -name: restore dependecies
      run: dotnet restore

    -name: Run unit test
      run: dotnet test